[package]
name = "solarscape-client"
version.workspace = true
edition.workspace = true

[dependencies]
solarscape-shared = { path = "../shared" }

bytemuck = "=1.14.0"
discord-rpc-client = "=0.4.0"
native-dialog = "=0.7.0"
wgpu = "=0.18.0"

clap = { version = "=4.4.9", features = [ "derive" ] }
winit = { version = "=0.29.4", features = [ "rwh_05" ] }

anyhow.workspace = true
hecs.workspace = true
log.workspace = true
nalgebra.workspace = true
thiserror.workspace = true
tokio.workspace = true
