[package]
name = "solarscape-client"
version.workspace = true
edition.workspace = true

[dependencies]
solarscape-shared = { path = "../shared" }

anyhow.workspace = true
bytemuck.workspace = true
hecs.workspace = true
log.workspace = true
nalgebra.workspace = true
tokio.workspace = true
wgpu.workspace = true
winit.workspace = true
