[package]
name = "solarscape-client"
version.workspace = true
edition.workspace = true

[dependencies]
solarscape-shared = { path = "../shared" }

bytemuck = "=1.14.0"
wgpu = "=0.17.1"
winit = "=0.28.7"

anyhow.workspace = true
hecs.workspace = true
log.workspace = true
nalgebra.workspace = true
tokio.workspace = true
