[package]
name = "solarscape-client"
version.workspace = true
edition.workspace = true

[dependencies]
solarscape-shared = { path = "../shared" }

bytemuck = "=1.14.0"
wgpu = "=0.18.0"
winit = { version = "=0.29.3", features = [ "rwh_05" ] }

anyhow.workspace = true
hecs.workspace = true
log.workspace = true
nalgebra.workspace = true
thiserror.workspace = true
tokio.workspace = true
