[workspace]
resolver = "2"
members = [
	"client",
	"macros",
	"server",
	"shared",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "=1.0.75"
log = "=0.4.20"
thiserror = "=1.0.50"

bincode = { version = "=2.0.0-rc.3", features = [ "serde" ] }
hecs = { version = "=0.10.4", features = ["serde"] }
nalgebra = { version = "=0.32.3", features = [ "serde-serialize" ] }
tokio = { version = "=1.34.0", features = [ "macros", "io-util", "net", "rt-multi-thread", "sync" ] }

[profile.dev.package."*"]
codegen-units = 1
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
