[workspace]
members = [
	"client",
	"server",
	"shared",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
env_logger = "0.10"
hocon = "0.9"
log = "0.4"
once_cell = "1"
thiserror = "1"
wgpu = "0.17"
winit = "0.28"

[workspace.dependencies.bincode]
version = "2.0.0-rc.3"
features = [ "serde" ]

[workspace.dependencies.nalgebra]
version = "0.32"
features = [ "serde-serialize" ]

[workspace.dependencies.serde]
version = "1"
features = [
	"derive",
]

[workspace.dependencies.tokio-util]
version = "0.7"
default-features = false

[workspace.dependencies.tokio]
version = "1"
features = [
	"macros",
	"net",
	"rt-multi-thread",
	"sync",
]

[profile.dev.package."*"]
codegen-units = 1
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
