[workspace]
resolver = "2"
members = [
	"client",
	"server",
	"shared",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "=1.0.75"
hecs = "=0.10.3"
log = "=0.4.20"
nalgebra = { version = "=0.32.3", features = [ "serde-serialize" ] }
thiserror = "=1.0.50"
tokio = { version = "=1.33.0", features = [ "macros", "io-util", "net", "rt-multi-thread", "sync" ] }

[profile.dev.package."*"]
codegen-units = 1
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
