[workspace]
members = [
	"client",
	"server",
	"shared",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
bincode = "2.0.0-rc.3"
hocon = "0.9"
once_cell = "1"
thiserror = "1"

[workspace.dependencies.integer-encoding]
version = "3"
features = [
	"tokio_async",
]

[workspace.dependencies.serde]
version = "1"
features = [
	"derive",
]

[workspace.dependencies.tokio-util]
version = "0.7"
default-features = false

[workspace.dependencies.tokio]
version = "1"
features = [
	"macros",
	"net",
	"rt-multi-thread",
	"sync",
]
