[package]
name = "solarscape-server"
version.workspace = true
edition.workspace = true

[dependencies]
solarscape-shared = { path = "../shared" }

hocon = { version = "=0.9.0", features = [ "serde-support" ] }
serde = { version = "=1.0.192", features = [ "derive" ] }

anyhow.workspace = true
hecs.workspace = true
log.workspace = true
nalgebra.workspace = true
thiserror.workspace = true
tokio.workspace = true
