[package]
name = "solarscape-server"
version.workspace = true
edition.workspace = true

[dependencies]
solarscape-shared = { path = "../shared" }

toml = { version = "=0.8.2", features = [ "parse" ] }

anyhow.workspace = true
hecs.workspace = true
log.workspace = true
nalgebra.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
