[package]
name = "solarscape-server"
version.workspace = true
edition.workspace = true

[dependencies]
solarscape-shared = { path = "../shared" }

anyhow.workspace = true
hocon.workspace = true
log.workspace = true
nalgebra.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
tokio.workspace = true
