[package]
name = "solarscape-server"
version.workspace = true
edition.workspace = true

[dependencies]
solarscape-shared = { path = "../shared" }

anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
