[package]
name = "solarscape-server"
version.workspace = true
edition.workspace = true

[dependencies]
solarscape-shared = { path = "../shared" }

once_cell = "=1.19.0"
paste = "=1.0.14"

hocon = { version = "=0.9.0", features = [ "serde-support" ] }
serde = { version = "=1.0.193", features = [ "derive" ] }

anyhow.workspace = true
hecs.workspace = true
log.workspace = true
nalgebra.workspace = true
thiserror.workspace = true
tokio.workspace = true
