[package]
name = "solarscape-server"
version.workspace = true
edition.workspace = true

[dependencies]
solarscape-shared = { path = "../shared" }

serde = { version = "=1.0.190", features = [ "derive" ] }
toml = { version = "=0.8.6", features = [ "parse" ] }

anyhow.workspace = true
hecs.workspace = true
log.workspace = true
nalgebra.workspace = true
thiserror.workspace = true
tokio.workspace = true
