[package]
name = "solarscape-shared"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde.workspace = true

nalgebra = { workspace = true, features = ["serde-serialize"] }

serde_with = "3"
