[package]
name = "solarscape-shared"
version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
log.workspace = true
serde.workspace = true

nalgebra = { workspace = true, features = ["serde-serialize"] }

serde_with = "3"
