[package]
name = "solarscape-backend-types"
version.workspace = true
edition.workspace = true
publish = false
build = "../build.rs"

[dependencies]
serde.workspace = true
sqlx.workspace = true

time = { version = "0.3", features = ["macros"] }
